### ISSUE TITLE
cogs.useful doesn’t load// is broken.

### ISSUE THREAD

**Issue by MendtheMiner** [Yurismm/Yuibot-rewrite#1]

**Comment by Mariobob** [comment]
Well then who broke it :thinking:

**Comment by Yurismm** [comment]
uh, ill see if i can look into it i guess

**Comment by Yurismm** [comment]
okay, next time don't add cogs that aren't done (eg, economy n stuff) and we'll be fine in the startup extensions

**Closing issue**

**Comment by Yurismm** [comment]
?

**Comment by Yurismm** [comment]
okay, ill fix it again, ill spend tonight on it

**Comment by Yurismm** [comment]
fixed
